name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/gh-pages' || github.ref == 'refs/heads/main')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug
        run: |
          ls -al
          git branch -a

      - name: Build and deploy
        run: |
          npm install
          npm run build

          if [ "${GITHUB_REF##*/}" == "main" ]; then
            git checkout gh-pages
            git pull origin gh-pages
            cp -r build/* .
            git add .
            git commit -m "Deploying to gh-pages"
            git push origin gh-pages
          fi
