name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy
        run: |
          # Replace these commands with your build commands
          npm install
          npm run build

          # Deploy the built code to gh-pages branch
          git checkout gh-pages
          git rm -rf .
          cp -r build/. .
          git add .
          git commit -m "Deploying to gh-pages"
          git push origin gh-pages
