name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug
        run: |
          ls -al
          git branch -a

      - name: Build and deploy
        run: |
          npm install
          npm run build

          git checkout gh-pages
          ls -al
          git status
          git pull origin gh-pages
          cp -r build/* .
          git add .
          git status
          git commit -m "Deploying to gh-pages"
          git push origin gh-pages
